// Copy the canonical Agent Skills from the monorepo's top-level `skills/` into
// `bestax-mcp/data/skills`, so the server can serve their bodies offline from
// the published tarball.
//
// `/skills` is the single source of truth; `data/skills` is generated and
// gitignored. Runs on `build`, `test`, `test:coverage`, `test:watch` and
// `prepack` — five entry points, and turbo runs the first three concurrently,
// which is what the locking below exists for. See "Concurrency" at the bottom.
//
// Three deliberate differences from create-bestax/scripts/sync-skills.mjs,
// which solves the same problem for the scaffolder:
//
//  1. The roster is READ, not listed. That file carries a hardcoded `SKILLS`
//     array, and skills/CLAUDE.md counts it among the five places the roster is
//     already duplicated (#385: nothing warns when a directory is absent).
//     Adding a sixth would be a sixth thing to forget. Any directory with a
//     SKILL.md ships.
//  2. No fs-extra. This package has one runtime dependency and no reason for a
//     second; node:fs/promises `cp` covers it.
//  3. This one is concurrency-safe. The scaffolder's copy is only reachable
//     from `build` and `prepack`, which never overlap, so it does not need to
//     be — but it has the same destructive shape, so if a third caller is ever
//     added there, port this.
//
// The MANIFEST (names, descriptions, reference lists) is committed instead, in
// data/skills.json — generated by scripts/gen-mcp-index.mjs. That is what the
// CI staleness gate watches, so a new or renamed skill still fails the build
// without a second committed copy of 390 KB of markdown bloating every diff.
import {
  cp,
  mkdir,
  readdir,
  readFile,
  rm,
  stat,
  writeFile,
} from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { setTimeout as sleep } from 'node:timers/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const skillsSrc = path.resolve(pkgRoot, '..', 'skills');
const skillsDest = path.join(pkgRoot, 'data', 'skills');

// Lock and freshness stamp live in their own directory, NOT loose in `data/`.
// `gen:mcp:check` runs `git add --intent-to-add --all bestax-mcp/data` and
// diffs the result, so an untracked file anywhere else under data/ would fail
// that gate. This path is gitignored alongside data/skills itself.
const stateDir = path.join(pkgRoot, 'data', '.sync-skills');
const lockDir = path.join(stateDir, 'lock');
const stampFile = path.join(stateDir, 'fingerprint');

// A sync is ~390 KB of file copies and takes tens of milliseconds. A lock held
// longer than this is a crashed run, not a slow one.
const LOCK_STALE_MS = 60_000;
const LOCK_TIMEOUT_MS = 120_000;
const LOCK_POLL_MS = 50;

if (!existsSync(skillsSrc)) {
  console.error(`[sync-skills] source not found: ${skillsSrc}`);
  process.exit(1);
}

const names = (await readdir(skillsSrc, { withFileTypes: true }))
  .filter(
    e => e.isDirectory() && existsSync(path.join(skillsSrc, e.name, 'SKILL.md'))
  )
  .map(e => e.name)
  .sort();

if (!names.length) {
  console.error(`[sync-skills] no skills found in ${skillsSrc}`);
  process.exit(1);
}

// Hash of every source path and its bytes. Content rather than mtime on
// purpose: a fresh clone or a branch switch rewrites mtimes without changing
// what should be copied, and re-copying is the cheap half — it is the
// destructive `rm` that has to be avoided while another process is reading.
async function fingerprintSource() {
  const hash = createHash('sha256');
  const walk = async (dir, rel) => {
    const entries = await readdir(dir, { withFileTypes: true });
    entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
    for (const entry of entries) {
      const abs = path.join(dir, entry.name);
      const key = `${rel}/${entry.name}`;
      if (entry.isDirectory()) {
        await walk(abs, key);
      } else {
        hash.update(key);
        hash.update(await readFile(abs));
      }
    }
  };
  for (const name of names) await walk(path.join(skillsSrc, name), name);
  return hash.digest('hex');
}

// `mkdir` without `recursive` is atomic and fails with EEXIST if the directory
// exists, which makes it a usable mutex with no dependency.
async function acquireLock() {
  const deadline = Date.now() + LOCK_TIMEOUT_MS;
  for (;;) {
    try {
      await mkdir(lockDir);
      return;
    } catch (err) {
      if (err.code !== 'EEXIST') throw err;
      try {
        const { mtimeMs } = await stat(lockDir);
        if (Date.now() - mtimeMs > LOCK_STALE_MS) {
          // Left behind by a killed run; reclaim it.
          await rm(lockDir, { recursive: true, force: true });
          continue;
        }
      } catch {
        // The holder released it between our mkdir and our stat. Retry.
      }
      if (Date.now() > deadline) {
        throw new Error(`[sync-skills] timed out waiting for lock: ${lockDir}`);
      }
      await sleep(LOCK_POLL_MS);
    }
  }
}

await mkdir(stateDir, { recursive: true });
const want = await fingerprintSource();

await acquireLock();
try {
  const have = await readFile(stampFile, 'utf8').catch(() => '');

  // The freshness check is load-bearing, not an optimisation. Without it the
  // second and third callers would re-run the destructive copy below while the
  // FIRST caller's jest is already reading data/skills, and `rm` would delete
  // the tree out from under it. Skipping the work when it is already done is
  // what actually makes concurrent callers safe; the lock alone would not.
  if (have.trim() === want && existsSync(skillsDest)) {
    console.log(`[sync-skills] up to date (${names.length} skills)`);
  } else {
    await rm(skillsDest, { recursive: true, force: true });
    await mkdir(skillsDest, { recursive: true });
    for (const name of names) {
      await cp(path.join(skillsSrc, name), path.join(skillsDest, name), {
        recursive: true,
      });
    }
    // Stamped last: a run killed mid-copy leaves no stamp, so the next caller
    // redoes the work rather than trusting a half-populated tree.
    await writeFile(stampFile, `${want}\n`);
    console.log(`[sync-skills] copied ${names.length} skills -> data/skills`);
  }
} finally {
  await rm(lockDir, { recursive: true, force: true });
}

// Concurrency
// -----------
// `pnpm all` runs `turbo run build typecheck test test:coverage`, and
// bestax-mcp's build, test and test:coverage scripts each invoke this file. On
// a cold turbo cache all three start within milliseconds of each other, and the
// original implementation went straight to `rm -rf data/skills` followed by a
// per-skill copy. Interleaving those produced a different error every run —
// ENOENT on copyfile, EEXIST on mkdir, ENOTEMPTY on rmdir — which read as three
// unrelated flakes rather than one race.
//
// It stayed hidden because a warm cache means only one of the three actually
// executes; it surfaces reliably right after a merge, on a fresh clone, and in
// CI, which is the worst possible time for it.
//
// Fixed here rather than in turbo.json because `pnpm --filter bestax-mcp test`
// has to keep working on its own — bestax-mcp/CLAUDE.md documents it — so the
// script cannot rely on a task graph to serialise its callers.
