// Copy the canonical Agent Skills from the monorepo's top-level `skills/` into
// `bestax-mcp/data/skills`, so the server can serve their bodies offline from
// the published tarball.
//
// `/skills` is the single source of truth; `data/skills` is generated and
// gitignored. Runs on `build` and `prepack`.
//
// Two deliberate differences from create-bestax/scripts/sync-skills.mjs, which
// solves the same problem for the scaffolder:
//
//  1. The roster is READ, not listed. That file carries a hardcoded `SKILLS`
//     array, and skills/CLAUDE.md counts it among the five places the roster is
//     already duplicated (#385: nothing warns when a directory is absent).
//     Adding a sixth would be a sixth thing to forget. Any directory with a
//     SKILL.md ships.
//  2. No fs-extra. This package has one runtime dependency and no reason for a
//     second; node:fs/promises `cp` covers it.
//
// The MANIFEST (names, descriptions, reference lists) is committed instead, in
// data/skills.json — generated by scripts/gen-mcp-index.mjs. That is what the
// CI staleness gate watches, so a new or renamed skill still fails the build
// without a second committed copy of 390 KB of markdown bloating every diff.
import { cp, mkdir, readdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const skillsSrc = path.resolve(pkgRoot, '..', 'skills');
const skillsDest = path.join(pkgRoot, 'data', 'skills');

if (!existsSync(skillsSrc)) {
  console.error(`[sync-skills] source not found: ${skillsSrc}`);
  process.exit(1);
}

const names = (await readdir(skillsSrc, { withFileTypes: true }))
  .filter(
    e => e.isDirectory() && existsSync(path.join(skillsSrc, e.name, 'SKILL.md'))
  )
  .map(e => e.name)
  .sort();

if (!names.length) {
  console.error(`[sync-skills] no skills found in ${skillsSrc}`);
  process.exit(1);
}

await rm(skillsDest, { recursive: true, force: true });
await mkdir(skillsDest, { recursive: true });

for (const name of names) {
  await cp(path.join(skillsSrc, name), path.join(skillsDest, name), {
    recursive: true,
  });
}

console.log(`[sync-skills] copied ${names.length} skills -> data/skills`);
