// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  apiSidebar: [
    {
      type: 'category',
      label: 'Components and APIs',
      items: [
        {
          type: 'category',
          label: 'Elements', // Title Case
          items: [{ type: 'autogenerated', dirName: 'api/elements' }],
        },
        {
          type: 'category',
          label: 'Components', // Title Case
          items: [{ type: 'autogenerated', dirName: 'api/components' }],
        },
        {
          type: 'category',
          label: 'Form', // Title Case
          items: [{ type: 'autogenerated', dirName: 'api/form' }],
        },
        {
          type: 'category',
          label: 'Columns', // Title Case
          items: [{ type: 'autogenerated', dirName: 'api/columns' }],
        },
        {
          type: 'category',
          label: 'Grid', // Title Case
          items: [{ type: 'autogenerated', dirName: 'api/grid' }],
        },
        {
          type: 'category',
          label: 'Layout', // Title Case
          items: [{ type: 'autogenerated', dirName: 'api/layout' }],
        },
        {
          type: 'category',
          label: 'Helpers', // Title Case
          items: [{ type: 'autogenerated', dirName: 'api/helpers' }],
        },
      ],
    },
    // { type: 'autogenerated', dirName: 'api' },
  ],
  componentSidebar: [{ type: 'autogenerated', dirName: 'components' }],
  guideSidebar: [{ type: 'autogenerated', dirName: 'guides' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
