/**
 * Data the API docs generator cannot derive at run time.
 *
 * The two maps below are GENERATED by `scripts/gen-api-sources.mjs` (run
 * `pnpm gen:api-sources`) and committed so the diff stays reviewable. Do not
 * hand-edit between the `<generated:…>` markers — regenerate instead.
 *
 * Everything is keyed by the page's frontmatter `title:` (the exported
 * component name), the same key `gen-component-catalog.mjs` uses.
 */

/**
 * Categories whose pages must follow the canonical section order.
 *
 * This is deliberately WIDER than `MANAGED_CATEGORIES`: consistent ordering is
 * a reader-facing promise across the whole reference, while generation only
 * makes sense where a page really is a component props table. `helpers/` is
 * ordered but not generated — see `GENERATED_EXEMPT`.
 */
export const ORDERED_CATEGORIES = new Set([
  'columns',
  'components',
  'elements',
  'form',
  'grid',
  'helpers',
  'layout',
]);

/**
 * Categories whose pages carry generated regions and are checked for staleness.
 */
export const MANAGED_CATEGORIES = new Set([
  'columns',
  'components',
  'elements',
  'form',
  'grid',
  'layout',
]);

/**
 * Pages that are ordered but never generated.
 *
 * `helpers/` documents hooks and utilities: four of its six pages use `## API`
 * with a signature block and have no props at all, and `config.md` / `theme.md`
 * carry hand-written prose sub-APIs under `## Props` that do not fit the
 * generated table model. They still get the canonical section order, so a
 * reader moving between reference pages sees one layout.
 */
export const GENERATED_EXEMPT = new Set(['helpers']);

/**
 * Which SCSS partial(s) register a component's CSS variables.
 *
 * `[]` means "the matcher found none" and suppresses the
 * `## CSS & Sass Variables` section. Usually that is correct — the component
 * has no SCSS, or it is a semantic wrapper (`Paragraph`, `Span`, the `Table`
 * family) with no Bulma root class — but it is a matcher verdict, not a
 * verification: LinkButton sat here as `[]` for months while its partial
 * registered four variables under a compound selector the matcher could not
 * parse (#464). Two guards close that gap: a component MISSING from this map
 * is a hard error in `gen-api-docs.mjs`, and a partial registering variables
 * that no entry here claims fails `check:conformance` (the orphan rule).
 *
 * `pkg: 'bulma'` resolves under node_modules/bulma; `pkg: 'repo'` is
 * repo-relative (the extras in bulma-ui/src/scss).
 */
// <generated:scss-sources>
export const SCSS_SOURCES = {
  Autocomplete: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_autocomplete.scss' },
  ],
  Avatar: [{ pkg: 'repo', path: 'bulma-ui/src/scss/components/_avatar.scss' }],
  Avatars: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/components/_avatars.scss' },
  ],
  Badge: [{ pkg: 'repo', path: 'bulma-ui/src/scss/components/_badge.scss' }],
  Block: [],
  Box: [{ pkg: 'bulma', path: 'sass/elements/box.scss' }],
  Breadcrumb: [{ pkg: 'bulma', path: 'sass/components/breadcrumb.scss' }],
  Button: [{ pkg: 'bulma', path: 'sass/elements/button.scss' }],
  Buttons: [],
  Card: [{ pkg: 'bulma', path: 'sass/components/card.scss' }],
  Carousel: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/components/_carousel.scss' },
  ],
  Cell: [],
  Checkbox: [{ pkg: 'repo', path: 'bulma-ui/src/scss/form/_checkbox.scss' }],
  Checkboxes: [],
  Code: [{ pkg: 'bulma', path: 'sass/base/generic.scss' }],
  Collapse: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/components/_collapse.scss' },
  ],
  Column: [{ pkg: 'bulma', path: 'sass/grid/columns.scss' }],
  Columns: [],
  Config: [],
  Container: [],
  Content: [{ pkg: 'bulma', path: 'sass/elements/content.scss' }],
  Control: [
    { pkg: 'bulma', path: 'sass/form/shared.scss' },
    { pkg: 'bulma', path: 'sass/utilities/controls.scss' },
  ],
  DateInput: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_dateinput.scss' },
    { pkg: 'bulma', path: 'sass/form/shared.scss' },
  ],
  DateInputBase: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_dateinput.scss' },
    { pkg: 'bulma', path: 'sass/form/shared.scss' },
  ],
  DateTimeInput: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_dateinput.scss' },
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_datetimeinput.scss' },
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_timeinput.scss' },
    { pkg: 'bulma', path: 'sass/form/shared.scss' },
  ],
  DateTimeInputBase: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_dateinput.scss' },
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_datetimeinput.scss' },
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_timeinput.scss' },
    { pkg: 'bulma', path: 'sass/form/shared.scss' },
  ],
  Delete: [{ pkg: 'bulma', path: 'sass/utilities/mixins.scss' }],
  Dialog: [{ pkg: 'repo', path: 'bulma-ui/src/scss/components/_dialog.scss' }],
  Divider: [],
  Dropdown: [{ pkg: 'bulma', path: 'sass/components/dropdown.scss' }],
  Emphasis: [],
  Field: [{ pkg: 'bulma', path: 'sass/form/tools.scss' }],
  Figure: [],
  File: [{ pkg: 'bulma', path: 'sass/form/file.scss' }],
  Footer: [{ pkg: 'bulma', path: 'sass/layout/footer.scss' }],
  Grid: [{ pkg: 'bulma', path: 'sass/grid/grid.scss' }],
  Hero: [{ pkg: 'bulma', path: 'sass/layout/hero.scss' }],
  Icon: [{ pkg: 'bulma', path: 'sass/elements/icon.scss' }],
  IconText: [{ pkg: 'bulma', path: 'sass/elements/icon.scss' }],
  Image: [],
  Input: [{ pkg: 'bulma', path: 'sass/form/shared.scss' }],
  InputBase: [{ pkg: 'bulma', path: 'sass/form/shared.scss' }],
  Level: [{ pkg: 'bulma', path: 'sass/layout/level.scss' }],
  Link: [],
  LinkButton: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/elements/_linkbutton.scss' },
  ],
  ListItem: [],
  Loading: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/components/_loading.scss' },
  ],
  Media: [{ pkg: 'bulma', path: 'sass/layout/media.scss' }],
  Menu: [{ pkg: 'bulma', path: 'sass/components/menu.scss' }],
  Message: [{ pkg: 'bulma', path: 'sass/components/message.scss' }],
  Modal: [{ pkg: 'bulma', path: 'sass/components/modal.scss' }],
  Navbar: [{ pkg: 'bulma', path: 'sass/components/navbar.scss' }],
  Notification: [{ pkg: 'bulma', path: 'sass/elements/notification.scss' }],
  Numberinput: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_numberinput.scss' },
  ],
  OrderedList: [],
  Pagination: [{ pkg: 'bulma', path: 'sass/components/pagination.scss' }],
  Panel: [{ pkg: 'bulma', path: 'sass/components/panel.scss' }],
  Paragraph: [],
  Pre: [{ pkg: 'bulma', path: 'sass/base/generic.scss' }],
  Progress: [{ pkg: 'bulma', path: 'sass/elements/progress.scss' }],
  Radio: [{ pkg: 'repo', path: 'bulma-ui/src/scss/form/_radio.scss' }],
  Radios: [],
  Rate: [{ pkg: 'repo', path: 'bulma-ui/src/scss/form/_rate.scss' }],
  Reveal: [{ pkg: 'repo', path: 'bulma-ui/src/scss/components/_reveal.scss' }],
  Section: [{ pkg: 'bulma', path: 'sass/layout/section.scss' }],
  Select: [
    { pkg: 'bulma', path: 'sass/form/select.scss' },
    { pkg: 'bulma', path: 'sass/form/shared.scss' },
  ],
  SelectBase: [
    { pkg: 'bulma', path: 'sass/form/select.scss' },
    { pkg: 'bulma', path: 'sass/form/shared.scss' },
  ],
  Sidebar: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/components/_sidebar.scss' },
  ],
  Skeleton: [{ pkg: 'bulma', path: 'sass/base/skeleton.scss' }],
  Slider: [{ pkg: 'repo', path: 'bulma-ui/src/scss/form/_slider.scss' }],
  Span: [],
  Steps: [{ pkg: 'repo', path: 'bulma-ui/src/scss/components/_steps.scss' }],
  Strong: [{ pkg: 'bulma', path: 'sass/base/generic.scss' }],
  SubTitle: [{ pkg: 'bulma', path: 'sass/elements/title.scss' }],
  Switch: [{ pkg: 'repo', path: 'bulma-ui/src/scss/form/_switch.scss' }],
  Table: [{ pkg: 'bulma', path: 'sass/elements/table.scss' }],
  Tabs: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/components/_tabs.scss' },
    { pkg: 'bulma', path: 'sass/components/tabs.scss' },
  ],
  Tag: [{ pkg: 'bulma', path: 'sass/elements/tag.scss' }],
  Taginput: [{ pkg: 'repo', path: 'bulma-ui/src/scss/form/_taginput.scss' }],
  Tags: [],
  Tbody: [],
  Td: [],
  TextArea: [
    { pkg: 'bulma', path: 'sass/form/input-textarea.scss' },
    { pkg: 'bulma', path: 'sass/form/shared.scss' },
  ],
  TextAreaBase: [
    { pkg: 'bulma', path: 'sass/form/input-textarea.scss' },
    { pkg: 'bulma', path: 'sass/form/shared.scss' },
  ],
  Tfoot: [],
  Th: [],
  Thead: [],
  Theme: [],
  TimeInput: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_timeinput.scss' },
    { pkg: 'bulma', path: 'sass/form/shared.scss' },
  ],
  TimeInputBase: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/form/_timeinput.scss' },
    { pkg: 'bulma', path: 'sass/form/shared.scss' },
  ],
  Title: [{ pkg: 'bulma', path: 'sass/elements/title.scss' }],
  Toast: [{ pkg: 'repo', path: 'bulma-ui/src/scss/components/_toast.scss' }],
  Tooltip: [
    { pkg: 'repo', path: 'bulma-ui/src/scss/components/_tooltip.scss' },
  ],
  Tr: [],
  UnorderedList: [],
};
// </generated:scss-sources>

/**
 * Pages whose `## Import` deliberately imports more than the page's own
 * component, because the component is not usable alone (`Table` with its cell
 * elements) or is always shown with a companion.
 */
// <generated:import-companions>
export const IMPORT_COMPANIONS = {
  Columns: ['Columns', 'Column'],
  Avatars: ['Avatars', 'Avatar'],
  Breadcrumb: ['Breadcrumb', 'Icon'],
  Carousel: ['Carousel', 'CarouselItem'],
  Dialog: ['Dialog', 'DialogContainer', 'dialog'],
  Toast: ['Toast', 'ToastContainer', 'toast'],
  ListItem: ['ListItem', 'UnorderedList', 'OrderedList'],
  OrderedList: ['OrderedList', 'ListItem'],
  Pre: ['Pre', 'Code'],
  Table: ['Table', 'Thead', 'Tbody', 'Tfoot', 'Tr', 'Th', 'Td'],
  UnorderedList: ['UnorderedList', 'ListItem'],
  Checkbox: ['Checkboxes', 'Checkbox'],
  Checkboxes: ['Checkboxes', 'Checkbox'],
  Control: ['Control', 'Input', 'Select', 'TextArea'],
  File: ['File', 'Icon'],
  Input: ['Input', 'Field', 'Control'],
  Radio: ['Radio', 'Radios', 'Control'],
  Radios: ['Radios', 'Radio'],
  Select: ['Select', 'Field', 'Control'],
  TextArea: ['TextArea', 'Field', 'Control'],
  Grid: ['Grid', 'Cell'],
};
// </generated:import-companions>
